name: "Setup"
description: "Install deps and cache"

inputs:
  node-version:
    required: false
    default: "20"

outputs:
  cache-hit:
    description: "Cache hit result"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
